### ISSUE TITLE
New Comment Alert

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-itest#141]
New Comment Added Alert
When a new comment is added on the network, it'll be useful to be able to see that a new comment has been added, even if the Comment View is currently off. Show a message alert? With an option to toggle Comment View?

Currently a new comment being added by a network computer will be displayed and updated in real time if the comment is already open.  You'll see that the comment is marked (*) red to indicate it's new and unread.  But it does NOT show an alert window or message.  Is that necessary?

---

# TO DO

- [X] Show new "reply" vs new "comment"
- [X] Show real-time update  
- [X] Show session update -- last few comments added.
- [x] Show unread comments
- [x] Show replies to ME
- [x] Actionable
   - [x] If a node/edge/comment is being edited, do not open the comment
   - [x] If the source reference is closed, open it
   - [x] If the comment is closed, open it
   - [x] Scroll to the updated current comment
- [x] Mark all comments read
- [x] Set duration of popup via template

**Comment by jdanish** [comment]
@benloh I'll add a follow-up issue that we think it will be helpful to distinguish between a new comment and a new reply (defined as a reply to my model in meme, or to my comment in either system). 

The other idea we had is that a) popups would be distracting, but for both apps it'd be nice to display a number of new comments and number of new replies. In Net.Create, in the top right near the token, and in meme in the models list screen where you first log in.

**Comment by benloh** [comment]
@jdanish A couple of design questions here.


A. Real-time updates vs Historical updates or both?

For the new comment alert, are you thinking...

1. Real-time updates where while you have Net.Create open, if someone else adds a comment or reply, you get a notice at the top of the screen?  e.g.

![Image](https://github.com/netcreateorg/netcreate-itest/assets/1403057/75e48c35-38e3-4df7-9bcb-de94c556224b)

or

2. Historical updates where the first time you log in after a period of inactivity you see some kind of count of the number of new comments and replies?

or both?
 

B. Actionable?  Findable?

The other challenge with this is once you see the alert, what action, if any, should the user take?
* Do you want to be able to click the alert to open up the new comment in the context of the parent node/edge?  (What happens if you're currently editing or looking at something else?)
* Do we need to provide contextual information, e.g. comment added to node XYZ?
* And if not, how should users find the new message?  Do they have to open up individual nodes?  Do we have a comment activity log that someone can browse through to open up the comments for review?

Or perhaps it's not necessary to be able to take an action?  This can get hairy pretty quickly.

**Comment by jdanish** [comment]
> A. Real-time updates vs Historical updates or both?

I think both. It's quite possible that Kalani comments on my node either while I am editing, or in-between sessions and we'd want me to realize it, at least if I glance at the right spot.

> B. Actionable? Findable?

It's messy, agreed. How about this (new idea): instead of a top right of whole interface indicator, just put an indicator on the node and / or edge table that there is a new comment within, and then the user can open the table and sort if needed to see what's new?  In the case of MEME it'll still just be on the level of the model (from the main menu) so you still need to find it inside the model, but that's not THAT hard, I think?  

Either way, once we have a way of opening the comment table, it'll help find the spot if needed.

**Comment by jdanish** [comment]
In case it is not obvious, the red dot / icon change in real-time is awesome. It's just the cases that you are busy doing something else or reading some other unrelated comment that want to make sure you can see there is a new one at a glance. Note that we ruled out popups as too distracting.

**Comment by benloh** [comment]
That screenshot I sent is actually from a working prototype.  So let me get that out to you try.  And then we can discuss / explore how to enhance that.  I think we might want to tackle thinking through what a full comment list might be.  That'd be the natural expansion of the alert.

**Comment by jdanish** [comment]
Ah, OK. So then the answer would be that ideally it will be actionable in some reasonable manner. Looking forward to it!

**Comment by benloh** [comment]
@jdanish thinking through new comment alerts...if you log out and back in, we want to see which comments have been added.  The question is, 

1. Does this include all unread comments? Or...
2. Should it only show comments that have been added since the last session even if there are other comments that are as yet unread?  I would think it's simpler to just show all unread comments rather than trying to differentiate between new and unread?  Unless...
3. Do you expect everyone to have read every comment?  Or is it OK to leave a bunch of comments unread?  This has an impact on what we show and how we show it.

**Comment by jdanish** [comment]
This is why I think it is important to distinguish between comment types. I'd want to know a) there are some unread comments, but b) the really important ones are ones that respond directly to me (or my model in meme).

So, something like:

5 [total unread symbol]
3 [unread replies symbol]

I think we want to see all unread comments, but have an option to maybe mark them read if you don't actually read them?

I don't expect everyone to read them all and it is fine to leave some unread. I just like being able to clear them because I find it annoying personally to have that badge sitting there.

Note: I don't think anyone cares how many are newly unread since last login. So if I logged out with 3 unread, and log back in with 5 unread, that's fine. The 5 is what is important. I don't need to see "2 were added".

**Comment by benloh** [comment]
Thanks, that's helpful.

For the real time update, I just added a prototype that will show the currrent update along with  "Recent Comments..." button.  And a placeholder link for opening the comment.

![Image](https://github.com/netcreateorg/netcreate-itest/assets/1403057/25e2c732-76a6-4d7f-ad8b-6ab9e2a4a7a4)

If you click on the button, you'll see all the comments added during the session.

![Image](https://github.com/netcreateorg/netcreate-itest/assets/1403057/a1c84a2c-ab5a-449b-a59b-d76252f8e568)

This works in the current `comment-status` branch.

**Comment by jdanish** [comment]
Yeah, that's cool. Also, you have too many comments.

**Comment by benloh** [comment]
> This is why I think it is important to distinguish between comment types. I'd want to know a) there are some unread comments, but b) the really important ones are ones that respond directly to me (or my model in meme).
> So, something like:
> 5 [total unread symbol]
> 3 [unread replies symbol]

So thinking this through some more...

#### Comment Status View
1. When you first open a graph, you'll see a pop up window that shows:
```
 > 5 unread comments
 > 3 unread replies
```
2. You can click a disclosure triangle to view the list of comments:
```
 > 5 unread comments
 v 3 unread replies
       #32 BlueGroup "This is stupid"
       #33 RedGroup "I know you are but what am I?"
       #42 BlueGroup "I have the answer!"
```
3. You can click any of those comments to view the source and the comment.
   - If the source (e.g. node/edge) is not open, open it
   - If the comment is not open, open it
   - Scroll down to the comment.
   - If a node or edge or comment is being edited, you cannot click on the comment.
4. You probably want to review the comment status, so perhaps we make a permanent "Comments" button in the navbar so that you can re-open the comment status view at any time.

> b) the really important ones are ones that respond directly to me (or my model in meme).

Are you saying that our comment status view would differentiate between general replies to other people vs replies directly to one of your comments?  If so, how do we distinguish that?  e.g. is it considered a reply only if you are the source of the root?  Or what if you're in part of a thread?  e.g. Sri makes a root comment, I reply, then you reply -- both you and I are replying to Sri's root, but you might be replying to Sri or to me -- we currently do not make that distinction since it's only one level deep.  So do I get a notice that you replied to my comment?  And does Sri get a notice too?  I worry that this is getting too complex.

**Comment by jdanish** [comment]
Yes, though ...

You said:
> When you first open a graph, you'll see a pop up window that shows:

Also: 
> You probably want to review the comment status, so perhaps we make a permanent "Comments" button in the navbar so that you can re-open the comment status view at any time.

That's why I am thinking that the status popup is just for new stuff when you are already logged in, that happens in real-time, but that the "comments" button is always visible. If it contains information, then it does double-duty because when I login I see the high level summary. Something like the attached, but with icons instead of N and R.

<img width="556" alt="Screenshot 2024-04-15 at 1 51 20 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/5f60859e-fbd4-41e4-b3ae-450ac34ee3a4">

This would mean we need a social practice of "look at the top right" when we first log in. If we do, we notice there is some new stuff and can click through. If we don't, maybe we are busy, so that's OK since that number won't change / go away until we view it.

**Comment by jdanish** [comment]
Sorry, I like your sample of what the list looks like. Note that it starts to overlap with the overall functionality that we had in mind for the comment list, with the only difference being that the entity isn't displayed. Meaning, we could also imagine a version that has:

```
v 3 unread replies
       Node 1, #32 BlueGroup "This is stupid"
       Node 1, #33 RedGroup "I know you are but what am I?"
       Edge 1, #42 BlueGroup "I have the answer!"
```

It'll start getting crowded, though. Thoughts?  I can ask the team for feedback or we can just try it depending on how hard it is?

**Comment by benloh** [comment]
> it does double-duty because when I login I see the high level summary.

I was thinking we would auto-open the summary when you first open the graph if there are any unreads.  That should be fairly easy to do.

> It'll start getting crowded, though. Thoughts? I can ask the team for feedback or we can just try it depending on how hard it is?

I believe all the data is there so it should be fairly easy to do.  It certainly makes sense to identify the source.  

I was thinking of putting the "3N 2R" button to the LEFT of the user name mostly because it'll keep the user name in a consistent position.  Otherwise alerts would constantly shift everything  back and forth.  But again, easy enough to try either way.

The other consideration is to figure out where/how to display a comment on the overall project.  But we probably want to make the project  name more prominent somewhere anyway and we can add the comment to that, more similar to MEME.


> overlap with the overall functionality that we had in mind for the comment list

Yes, which is why I was putting all this together into a single design issue.  I think the real question here is what you want that display to be.  Are we simply listing every single comment and reply along with the source node/edge?  That can be a really long list.  I was thinking we could add a button or disclosure triangle to the comment status view to show ALL the comments.  That way all the functionality is in one place.

**Comment by benloh** [comment]
I think this got lost in my reply because everything was marked as a reply.  

> b) the really important ones are ones that respond directly to me (or my model in meme).

Are you saying that our comment status view would differentiate between general replies to other people vs replies directly to one of your comments? If so, how do we distinguish that? e.g. is it considered a reply only if you are the source of the root? Or what if you're in part of a thread? e.g. Sri makes a root comment, I reply, then you reply -- both you and I are replying to Sri's root, but you might be replying to Sri or to me -- we currently do not make that distinction since it's only one level deep. So do I get a notice that you replied to my comment? And does Sri get a notice too? I worry that this is getting too complex.

**Comment by jdanish** [comment]
Putting the comment status / button to the left of the login makes sense. Let's try that.

Yes, a project name / comment similar to meme works for me for location of that.

Re: The comment "list" ... I am starting to think that in Net.Create, we may not need it because you can see the comments within the node / edge tables. Thinking about MEME, I think we'd want all comments also nested by specific entities, outcomes, and processes (similar to nodes / edges, but maybe they are a column rather than a full tab)... 

I had originally been thinking we'd want to treat it as "data" and show "all" the information (e.g., assume you might sort comments by date) but now I am thinking that just knowing there is a comment on a specific thing, and then being able to see that thread makes the most sense. 

We might also want some basic "find" that finds a specific comment, but ...  maybe let's hold off on that and assume that we'll be looking at the thread on a specific thing (node, edge, entity, whatever) and not need to find "that comment about fish" ...  and if we did, we'd look at "Fish". 

For the last one ... I assume that if we have:

```
A: Sri (previously read)
... R1: Joshua (previously read)
... R2: Ben (new)
B: Kalani (previously read)
```
I would treat R2 as a reply to everyone above, so Sri and Joshua are notified of Ben's reply. My instinct is to say that Kalani is not notified because she was not in that same chain. Also, no one is told that Kalani replied to them when she posts her comment. But they do see it as "new" (lower priority), since we assume if she wanted them notified she'd have hit reply, not comment. So, in short, if you press "reply" it notifies everyone in that thread, but if you press "comment" no one is notified in net.create. However, in meme you'd be notified if you are the model owner. In net.create there is no single "owner" for commenting purposes. Or we'd have a "treat as owner" flag in both, maybe?  So that a teacher in net.create could indicate in the template they are the "owner" from the standpoint of being notified?

However, if it is easier to say "Notify Kalani because she had a comment on the same node / edge" I'm OK with that, but this would still be treated as a "reply" whereas for Selena it'd just be "new" because she hasn't previously done any commenting on this node. So if Selena was going to ignore anything, she would ignore Kalani but I might want to know. Though I prefer the prior more nuanced solution.

**Comment by benloh** [comment]
So this suggests that we want to show three numbers:
* replies to me
* new comments
* unread comments

Something like this?

![screenshot_1490](https://github.com/netcreateorg/netcreate-itest/assets/1403057/aafd4be9-191a-49e7-b227-809f676fdc57)

**Comment by jdanish** [comment]
I was thinking about combining new and unread into one category (unread, since new is unread too) to save space.

Joshua

**Comment by benloh** [comment]
Ah right.  We still have the "new" count in the real-time updates.

**Comment by jdanish** [comment]
Yup. And in most cases I think the real question is are they new to me (unread) or not.

**Comment by benloh** [comment]
Marked all items done.  Remaining to dos have been converted into issues.
