### ISSUE TITLE
CSS padding for group no and new-comment display overlaps (cross-browser compatibility)

### ISSUE THREAD

**Issue by kalanicraig** [netcreateorg/netcreate-itest#171]
Padding for access-token group-no display doesn't have enough padding in Safari

<img width="390" alt="Screenshot 2024-04-22 at 2 35 25 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/9748020/d454a166-1d23-4c45-b46d-15b5a3086aa3">

**Comment by jdanish** [comment]
Note that should read "Group: 1" not JP: 1

**Comment by benloh** [comment]
@jdanish @kalanicraig What version of Safari are you using and what is your window size?  I'm not seeing it with version 17.4.1.

**Comment by jdanish** [comment]
Version 16.6 (18615.3.12.11.2)

However I just confirmed this happens in my chrome now too.

Normally, I create a token with 1 character per field so something like: 1-1-EK2
Kalani found this by using a full group name. If you try: GROUP1-PROJECT-X4Q it happens. I just never noticed it because I was using such small names. 

It definitely happens when I run full-screen even, but if it helps try the Chromebook size?
<img width="729" alt="Screenshot 2024-04-25 at 3 36 18 PM" src="https://github.com/netcreateorg/netcreate-itest/assets/5529898/c4e0b7e1-e6e9-44a9-bc71-0252a7a0584c">

**Comment by benloh** [comment]
Ah, got it.
