### ISSUE TITLE
BUG: Export and Re-import fail if certain attributes are hidden

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#296]
Just exported a nodes table, made edits, and re-imported. Received the following error:

`Error trying to import ELAConnectionsS2024P2nodesDeID.csv!
Missing keys: "ID", "Info", "InfoSource", "Created By", "Updated By"
Keys found in file: Label, NodeType, Notes, Provenance, Comments, Degrees, Created, Updated`

I was able to work around it by adding / making visible all of those keys, etc. 

I believe that ID should always be exported even if hidden, and the others should not need to be present?

Urgent as-in, must do before grant ends, not as-in, need this week or month even as I can work around it.

**Comment by benloh** [comment]
Problem files are here: http://159.203.177.172/graph/ELA_Connections_S2024_P2_DeID/#/edit/ELA-A-WED/?admin=true
[Archive.zip](https://github.com/user-attachments/files/18213322/Archive.zip)

**Comment by benloh** [comment]
To close this off...there were three problems.
1.  Exporting and re-importing templates were broken due to hidden fields not being exported. #296 #297.  Fixed with #308.
2. Exporting and re-importing were causing errors due to interim state updates as templates transitioned from one type to another #311 [# 284 comment](https://github.com/netcreateorg/netcreate-itest/issues/284#issuecomment-2558114447).  Fixed with #308 in c0ad2541a84fe12ac999e5056d8f5d895d1fa89e.
3. Importing a template with custom fields would cause JSON Editor to revert to predefined schemas, removing the custom fields.  The main comment in issue #284 is an example of the error.  Issue #115 is the proper description.

**Comment by benloh** [comment]
@jdanish I've closed this issue to clean things up.  But you might do a test with `dev-next` with the `ELAConnectionsS2024P2` data to make sure.
