### ISSUE TITLE
BUG: Edge attributes of date, citation, and source ignore hidden property?

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#297]
Create a default network, mark those fields as hidden=true, open network. They still appear in the edge table. Delete them, and they go away.

**Comment by benloh** [comment]
@jdanish this should be fixed by `dev-bl/fix-export` #308

**Comment by jdanish** [comment]
This does not appear fixed.

Created a brand new network "TestNew" which shows citation. Changed attribute:


[edgeDefs.citation]
type = "string"
displayLabel = "Citation"
exportLabel = "Citation"
help = 'Source Book.Chapter (e.g. "Part 2 06.03")'
isProvenance = false
hidden = true

Re-run with this new setting - it does not disappear. Delete citation entirely, and it goes away.

**Comment by benloh** [comment]
Sorry, tables were not paying attention to the hidden field either.
37be77492bad2b36896547b1732a42638b4f9936

**Comment by benloh** [comment]
To close this off...there were three problems.
1.  Exporting and re-importing templates were broken due to hidden fields not being exported. #296 #297.  Fixed with #308.
2. Exporting and re-importing were causing errors due to interim state updates as templates transitioned from one type to another #311 [# 284 comment](https://github.com/netcreateorg/netcreate-itest/issues/284#issuecomment-2558114447).  Fixed with #308 in c0ad2541a84fe12ac999e5056d8f5d895d1fa89e.
3. Importing a template with custom fields would cause JSON Editor to revert to predefined schemas, removing the custom fields.  The main comment in issue #284 is an example of the error.  Issue #115 is the proper description.

**Comment by benloh** [comment]
@jdanish I've closed this issue to clean things up.  But you might do a test with `dev-next` to make sure.  There were a multiple inter-related issues.  Hopefully they're finally cleaned up.
