### ISSUE TITLE
Move connection type between source and target in edges table

### ISSUE THREAD

**Issue by jdanish** [netcreateorg/netcreate-itest#64]

**Comment by jdanish** [comment]
@benloh also flagging this as relevant to our Spring implementation.

**Comment by benloh** [comment]
@jdanish I'm not sure what you're asking for here. Are you just wanting to change the sort order of the table columns so that it goes `<source> | <type> | <target>`?

This is a little odd mostly because officially only `source` and `target` are built-in fields.  Everything else, including `type`, is an optional attribute field.  So currently the Edge Table first displays the built-in field types, followed by the optional/custom attribute fields in the order that they are defined in the template.  Moving `type` in the middle would mean we're elevating the `type` field to a special custom order. 

But implementing this means that if you have a custom type field called something else, e.g. `relationship`, we would not be able to insert it between `source` and `target`.  

Using the first `option` field would not work if you have more than one `option` field.  And I'd hate to add another field definition / option just to show it first.  

My inclination is to just have a special exception that any field called `type` will be shown between `source` and `target`.  Everything else gets hairy.  Does that work?

**Comment by jdanish** [comment]
Yes that is what we are asking for because often our data is something like Ben, Food, eats and it’ll be more intuitive for kids to see it as Ben eats Food.

I’d think that type is always required even if it gets renamed - don’t we always need an edge type ? 

Either way, yes a special case is AOK.

**Comment by benloh** [comment]
Implemented with #92
